version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iptv-proxy-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "9261:9261"
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    depends_on:
      - mysql
      - redis
    networks:
      - iptv-network

  mysql:
    image: mysql:8.0
    container_name: iptv-proxy-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: iptv_proxy
      MYSQL_USER: iptv_proxy
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - iptv-network

  redis:
    image: redis:alpine
    container_name: iptv-proxy-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - iptv-network

networks:
  iptv-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
